### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 2d

### ISSUE THREAD

**Issue by rkamalakannan** [cassandre-tech/cassandre-trading-bot#1035]
**Release number**
Cassandre release you are using. 6.0.0

**Describe the bug**
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 2d
Trying to use Kraken Exchange using Cassendre. I have configured the app.properties like below as per the guides.

cassandre.trading.bot.exchange.driver-class-name=org.knowm.xchange.kraken.KrakenExchange

However it is throwing out the below error.

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
21:13:36 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tech.cassandre.trading.bot.configuration.ExchangeAutoConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Illegal base64 character 2d
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at com.mycompany.bot.Application.main(Application.java:14)
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 2d
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:847)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at org.knowm.xchange.kraken.service.KrakenDigest.createInstance(KrakenDigest.java:29)
	at org.knowm.xchange.kraken.service.KrakenBaseService.<init>(KrakenBaseService.java:53)
	at org.knowm.xchange.kraken.service.KrakenMarketDataServiceRaw.<init>(KrakenMarketDataServiceRaw.java:31)
	at org.knowm.xchange.kraken.service.KrakenMarketDataService.<init>(KrakenMarketDataService.java:29)
	at org.knowm.xchange.kraken.KrakenExchange.initServices(KrakenExchange.java:19)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:108)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:130)
	at tech.cassandre.trading.bot.configuration.ExchangeAutoConfiguration.configure(ExchangeAutoConfiguration.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 17 common frames omitted

**To Reproduce**
Steps to reproduce the behavior.

app.properties:
 cassandre.trading.bot.exchange.driver-class-name=org.knowm.xchange.kraken.KrakenExchange

remove graphql dependency

**Expected behavior**
supposed to run without any issues.

**Comment by rkamalakannan** [comment]
It works ..  Issue with API Permissions!
