### ISSUE TITLE
Gemini exchange. cannot get trade history

### ISSUE THREAD

**Issue by NarimanAB** [cassandre-tech/cassandre-trading-bot#459]
**Describe the bug**
cannot get trade history from gemini exchange

00:39:31.433 [pool-2-thread-1] DEBUG tech.cassandre.trading.bot.service.xchange.TradeServiceXChangeImplementation - TradeService - Getting trades from exchange
00:39:33.306 [pool-2-thread-1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
org.knowm.xchange.exceptions.ExchangeException: CurrencyPair must be supplied
	at org.knowm.xchange.gemini.v1.service.GeminiTradeService.getTradeHistory(GeminiTradeService.java:113)
	at tech.cassandre.trading.bot.service.xchange.TradeServiceXChangeImplementation.getTrades(TradeServiceXChangeImplementation.java:250)
	at tech.cassandre.trading.bot.batch.TradeFlux.getNewValues(TradeFlux.java:50)
	at tech.cassandre.trading.bot.util.base.batch.BaseExternalFlux.update(BaseExternalFlux.java:23)
	at tech.cassandre.trading.bot.configuration.ScheduleAutoConfiguration.tradeFluxUpdate(ScheduleAutoConfiguration.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**
configure account/access (I used sandbox account) to gemini exchange, run application

**Expected behavior**
no exception in the logs, if the feature is not supported it just should not be enabled, or the there should be a way to disable it 

**Screenshots**
none

**Additional context**
gemini requires CurrencyPair, while other exchanges do not, other exchanges can require other additional parameters. Can I have my implementation of TradeServiceXChangeImplementation? how can it be extended?

**Comment by NarimanAB** [comment]
I see that all autoconfiguration factories here https://github.com/cassandre-tech/cassandre-trading-bot/tree/development/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/configuration
has post-construct annotated method where all those *XChange implementations are initialized via explicit "new". For example: https://github.com/cassandre-tech/cassandre-trading-bot/blob/a1224370858fa1ad444247f48e7449d97a24d032/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/configuration/ExchangeAutoConfiguration.java#L171
Why they are not spring managed beans? How can someone for example implement custom MarketService?

In my case, I need TradeServiceXChangeImplementation implementation, the only way I see to have it now is to disable all these autoconfigurations smth like
`@SpringBootApplication(exclude = { ExchangeAutoConfiguration.class, ScheduleAutoConfiguration.class,
	StrategyAutoConfiguration.class, StrategyAutoConfiguration.class})`
	
then extend ExchangeAutoConfiguration and overwrite the method post-construct annotated method - quite a lot of work. very difficult to extend.

Much more easier to have an option to have a custom TradeServiceXChangeImplementation bean injected into ExchangeAutoConfiguration at the application start.

**Comment by straumat** [comment]
I will create a sandbox account on gemini and make a test. I hope to do it by friday.

**Comment by straumat** [comment]
Hi @NarimanAB, I tried to implement integration tests but it seems Gemini Xchange API doesn't support placeMarketOrder. Have you seen that ? Can you tell me more how you are using it ? Thx

[https://github.com/knowm/XChange/pull/2695](https://github.com/knowm/XChange/pull/2695)

**Comment by NarimanAB** [comment]
I am just configured the bot for gemini snadbox account and started it (empty strategy, just log events). The issue I try describe is not truly related to gemini. each exchange can have its own specifics, you just cannot cover all of them. That is why I though that as it is a spring application after all why not give users a chance to easily extend the application. Why I cannot easily implement vertion of ExchangeServiceXChangeImplementation and pass it to the autoconfiguration factory you created? 

I "fixed" the issue by putting `params.setCurrencyPair(CurrencyPair.BTC_USD); to `ExchangeServiceXChangeImplementation  somewhere before line https://github.com/cassandre-tech/cassandre-trading-bot/blob/8c989a0703eda99bbeec7bb3e3e38a2c95238aad/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/service/xchange/TradeServiceXChangeImplementation.java#L251 
In my opinion all services under tech.cassandre.trading.bot.service.xchange could be exposed as beans, and/or autoconfiguration should only initiate defaults ones if no other instances are provided

**Comment by straumat** [comment]
@NarimanAB Hi, I exposed all the XChange services as beans. Can you tell me if it's fine for you?

**Comment by straumat** [comment]
@NarimanAB Hi, i made a fix that may fix your problem. Can you tell me what you think and if it works ? 
https://github.com/cassandre-tech/cassandre-trading-bot/commit/a7924d0b0eba2b9189ceae5fb0ad23146c9c035d
Thanks
