### ISSUE TITLE
Cannot run application with Binance API

### ISSUE THREAD

**Issue by zymonmikolaj** [cassandre-tech/cassandre-trading-bot#478]
**Describe the bug**
Cannot run application when binance exchange is set. Version 4.0.1

`21:18:31 - Unexpected error occurred in scheduled task
org.knowm.xchange.exceptions.ExchangeException: You need to provide the currency pair to get the user trades.
	at org.knowm.xchange.binance.service.BinanceTradeService.getTradeHistory(BinanceTradeService.java:233)
	at tech.cassandre.trading.bot.service.xchange.TradeServiceXChangeImplementation.getTrades(TradeServiceXChangeImplementation.java:250)
	at tech.cassandre.trading.bot.batch.TradeFlux.getNewValues(TradeFlux.java:50)
	at tech.cassandre.trading.bot.util.base.batch.BaseExternalFlux.update(BaseExternalFlux.java:23)
	at tech.cassandre.trading.bot.configuration.ScheduleAutoConfiguration.tradeFluxUpdate(ScheduleAutoConfiguration.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**To Reproduce**
In application.properties:
`cassandre.trading.bot.exchange.name=binance`

In pom.xml:
```
<dependency>
	<groupId>org.knowm.xchange</groupId>
	<artifactId>xchange-binance</artifactId>
	<version>5.0.6</version>
</dependency>
```

**Expected behavior**
Application is up and running.

**Comment by straumat** [comment]
Hi, I added a parameter to the method but I can't really test it as I don't have a Binance account. Can you see if it works for you ?
