### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by intothemoonlite** [cassandre-tech/cassandre-trading-bot#674]
**Describe the bug**
Running backtests, the following error pops up:

```
23:00:30 - Scheduler worker in group main failed with an uncaught exception
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException
Caused by: java.lang.NullPointerException: null
	at tech.cassandre.trading.bot.dto.position.PositionDTO.tradeUpdate(PositionDTO.java:252)
	at tech.cassandre.trading.bot.service.intern.PositionServiceImplementation.lambda$tradeUpdate$1(PositionServiceImplementation.java:206)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at tech.cassandre.trading.bot.service.intern.PositionServiceImplementation.tradeUpdate(PositionServiceImplementation.java:205)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:476)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:254)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runBackfused(FluxPublishOn.java:483)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:520)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
Use this strategy to backtest using the attached btc-usdt 1d tickers:

```
    ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
    EMAIndicator shortMa = new EMAIndicator(closePrice, 5);
    EMAIndicator neutralMa = new EMAIndicator(closePrice, 10);
    EMAIndicator longMa = new EMAIndicator(closePrice, 14);

    return new BaseStrategy(
        (new OverIndicatorRule(shortMa, neutralMa).or(new OverIndicatorRule(shortMa, longMa))), new UnderIndicatorRule(shortMa, neutralMa));
```
[tickers-btc-usdt.csv](https://github.com/cassandre-tech/cassandre-trading-bot/files/6772987/tickers-btc-usdt.csv)

**Comment by straumat** [comment]
@intothemoonlite hi, can you tell me which release of Cassandre you are using ? Thx

**Comment by intothemoonlite** [comment]
Hi @straumat I'm using 4.3.0. 5.0.0 backtests don't run yet for me.

**Comment by straumat** [comment]
@intothemoonlite  Sorry to completely reproduce the problem, I also need your code for `getDelayBetweenTwoBars()` and `getMaximumBarCount()`. Thanks.

**Comment by intothemoonlite** [comment]
Hi @straumat  please see below:

```
@Override
  public Duration getDelayBetweenTwoBars() {
    // Delay between two bars.
    return Duration.ofDays(DURATION);;
  }

@Override
  public int getMaximumBarCount() {
    // Number of bars to keep.
    return 20;
  }
```

**Comment by straumat** [comment]
Hi @intothemoonlite I made it work with 5.0.1-SNAPSHOT (and it's now super fast). I attached you the sources of the project.
[ta4j-strategy.zip](https://github.com/cassandre-tech/cassandre-trading-bot/files/6807766/ta4j-strategy.zip)

**Comment by intothemoonlite** [comment]
@straumat keen to test this out, thanks!! Will come back with some feedback.

**Comment by intothemoonlite** [comment]
Trying to build and I can't resolve the 5.0.1-SNAPSHOT dependency. I can however see 5.0.1 here: https://mvnrepository.com/artifact/tech.cassandre.trading.bot/cassandre-trading-bot-spring-boot-starter-test. Is that what I should use?

**Comment by straumat** [comment]
You can choose 5.0.1
