### ISSUE TITLE
Starting a Bot with a Currency-Pair where the Base-Currency amount is Zero results in a divide by zero error

### ISSUE THREAD

**Issue by TankWBY** [cassandre-tech/cassandre-trading-bot#761]
This happened when trying to trade Ethereum with an initial balance of 100USDT and 0ETH.

See stacktrace:

`Received information about a position status : PositionDTO(id=1, positionId=1, type=LONG, strategy=StrategyDTO(id=1, strategyId=1, type=BASIC_TA4J_STRATEGY, name=Simple ta4j strategy), currencyPair=ETH/USDT, amount=0E-52 ETH, rules=Stop gain at 25 % / Stop loss at 20 %, forceClosing=false, openingOrder=OrderDTO(id=1, orderId=DRY_ORDER_000000001, type=BID, strategy=StrategyDTO(id=1, strategyId=1, type=BASIC_TA4J_STRATEGY, name=Simple ta4j strategy), currencyPair=ETH/USDT, amount=0E-52 ETH, averagePrice=544.15000000 USDT, limitPrice=null, marketPrice=544.15000000 USDT, leverage=null, status=PENDING_NEW, cumulativeAmount=0E-52 ETH, userReference=null, timestamp=2021-09-28T12:09:35.857231800+02:00[Europe/Vienna], trades=[]), closingOrder=null, lowestGainPrice=null, highestGainPrice=null, latestGainPrice=null, status=OPENED)
2021-09-28 12:09:35.978 ERROR 34664 --- [assandre-flux-2] t.c.trading.bot.batch.TickerFlux         : TickerFlux encountered and error java.lang.ArithmeticException: / by zero
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.ArithmeticException: / by zero
Caused by: java.lang.ArithmeticException: / by zero
	at java.base/java.math.BigDecimal.divideAndRound(BigDecimal.java:4642)
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:5730)
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1636)
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1666)
	at tech.cassandre.trading.bot.dto.position.PositionDTO.calculateGainFromPrice(PositionDTO.java:196)
	at tech.cassandre.trading.bot.dto.position.PositionDTO.tickerUpdate(PositionDTO.java:302)
	at tech.cassandre.trading.bot.strategy.GenericCassandreStrategy.lambda$updatePositionsWithTickersUpdates$21(GenericCassandreStrategy.java:422)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at tech.cassandre.trading.bot.strategy.GenericCassandreStrategy.updatePositionsWithTickersUpdates(GenericCassandreStrategy.java:428)
	at tech.cassandre.trading.bot.strategy.BasicTa4jCassandreStrategy.tickersUpdates(BasicTa4jCassandreStrategy.java:113)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:476)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:267)
	at reactor.core.publisher.FluxCreate$LatestAsyncSink.drain(FluxCreate.java:954)
	at reactor.core.publisher.FluxCreate$LatestAsyncSink.next(FluxCreate.java:878)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at tech.cassandre.trading.bot.util.base.batch.BaseFlux.emitValues(BaseFlux.java:67)
	at tech.cassandre.trading.bot.util.base.batch.BaseFlux.update(BaseFlux.java:76)
	at tech.cassandre.trading.bot.configuration.ScheduleAutoConfiguration.tickerFluxUpdate(ScheduleAutoConfiguration.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by straumat** [comment]
@TankWBY HI do you know why you have zero ?

**Comment by TankWBY** [comment]
I didn't have time to debug too much into it, but I the issue arose when I had a trading user that had an initial ETH balance of 0 and it didn't occur when i set it to a very very small amount (i think 0.00001). (I was trading ETH/USDT for clearance)

The intention was to give the bot some "Pocket money" (in USDT) and let it loose on the market.

My best guess is, that at some point in the gain calculation there is a division where the divisor can be Zero. I didn't look too deep into the code though.
I actually had it happen once during a run as well (not on startup) so I assume that the issue can also occur if your strategy is so bad that your balance falls to zero.

**Comment by straumat** [comment]
@TankWBY from what I see, in my database structure, I store values as `numeric(16, 8)`, do you think you create a trade/position with a very small amount ? Can you give me the amount, the type of order and the currency pair that created this error? Thank you
