### ISSUE TITLE
ERROR 24308 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task  reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException Caused by: java.lang.NullPointerException: null 	at tech.cassandre.trading.bot.dto.position.PositionDTO.shouldBeClosed(PositionDTO.java:112) 

### ISSUE THREAD

**Issue by s-teamup** [cassandre-tech/cassandre-trading-bot#762]
**Release number**
<dependency>
			<groupId>tech.cassandre.trading.bot</groupId>
			<artifactId>cassandre-trading-bot-spring-boot-starter</artifactId>
			<version>2.0.1</version>
		</dependency>

**Describe the bug**
ERROR 24308 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException
Caused by: java.lang.NullPointerException: null
	at tech.cassandre.trading.bot.dto.position.PositionDTO.shouldBeClosed(PositionDTO.java:112) ~[cassandre-trading-bot-spring-boot-autoconfigure-2.0.1.jar:2.0.1]
	at tech.cassandre.trading.bot.service.PositionServiceImplementation.lambda$tickerUpdate$0(PositionServiceImplementation.java:80) ~[cassandre-trading-bot-spring-boot-autoconfigure-2.0.1.jar:2.0.1]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at tech.cassandre.trading.bot.service.PositionServiceImplementation.tickerUpdate(PositionServiceImplementation.java:81) ~[cassandre-trading-bot-spring-boot-autoconfigure-2.0.1.jar:2.0.1]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:476) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:267) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxCreate$LatestAsyncSink.drain(FluxCreate.java:954) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxCreate$LatestAsyncSink.next(FluxCreate.java:878) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
	at tech.cassandre.trading.bot.util.base.BaseFlux.emitValue(BaseFlux.java:53) ~[cassandre-trading-bot-spring-boot-autoconfigure-2.0.1.jar:2.0.1]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at tech.cassandre.trading.bot.util.base.BaseFlux.update(BaseFlux.java:60) ~[cassandre-trading-bot-spring-boot-autoconfigure-2.0.1.jar:2.0.1]
	at tech.cassandre.trading.bot.configuration.ScheduleAutoConfiguration.setupTickerFlux(ScheduleAutoConfiguration.java:73) ~[cassandre-trading-bot-spring-boot-autoconfigure-2.0.1.jar:2.0.1]
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

**Comment by straumat** [comment]
Can you move to the latest release ?

**Comment by s-teamup** [comment]
Yes, did not find this issue.
