### ISSUE TITLE
AccountFlux encountered and error EAPI:Invalid nonce

### ISSUE THREAD

**Issue by xblaatx** [cassandre-tech/cassandre-trading-bot#789]
**Release number**
5.0.5

**Describe the bug**
When I start the bot. It can run hours without any exception. and all of the sudden it starts giving exceptions with an interval of 2 minutes. 

**To Reproduce**
Start bot and wait for a few hours.

**Expected behavior**
No exceptions

**Additional context**

org.knowm.xchange.exceptions.NonceException: EAPI:Invalid nonce
	at org.knowm.xchange.kraken.service.KrakenBaseService.checkResult(KrakenBaseService.java:85)
	at org.knowm.xchange.kraken.service.KrakenAccountServiceRaw.getKrakenTradeBalance(KrakenAccountServiceRaw.java:149)
	at org.knowm.xchange.kraken.service.KrakenAccountServiceRaw.getKrakenTradeBalance(KrakenAccountServiceRaw.java:160)
	at org.knowm.xchange.kraken.service.KrakenAccountService.getAccountInfo(KrakenAccountService.java:44)
	at tech.cassandre.trading.bot.service.UserServiceXChangeImplementation.getUser(UserServiceXChangeImplementation.java:44)
	at tech.cassandre.trading.bot.batch.AccountFlux.getNewValues(AccountFlux.java:31)
	at tech.cassandre.trading.bot.util.base.batch.BaseFlux.update(BaseFlux.java:76)
	at tech.cassandre.trading.bot.configuration.ScheduleAutoConfiguration.accountFluxUpdate(ScheduleAutoConfiguration.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xblaatx** [comment]
Didn't get the EAPI:Invalid nonce errors anymore.
