### ISSUE TITLE
Precision is over the maximum defined for an asset

### ISSUE THREAD

**Issue by xblaatx** [cassandre-tech/cassandre-trading-bot#831]
**Release number**
5.0.6

**Describe the bug**
when cassandre tries to sell a long position it retrieves an error more decimal positions are used then allowed

**To Reproduce**
any strategy with an createLongPosition for the SHIB asset

**Additional context**

2021-11-30 14:13:15.033 ERROR 1 --- [assandre-flux-2] s.PositionServiceCassandreImplementation : Position 1 not closed: TradeService - Error calling createMarketOrder for 2383222.00000000 SHIB/EUR: Precision is over the maximum defined for this asset. (HTTP status code: 400)
org.knowm.xchange.exceptions.ExchangeException: Precision is over the maximum defined for this asset. (HTTP status code: 400)
	at org.knowm.xchange.binance.BinanceErrorAdapter.adapt(BinanceErrorAdapter.java:49)
	at org.knowm.xchange.binance.service.BinanceTradeService.placeOrder(BinanceTradeService.java:158)
	at org.knowm.xchange.binance.service.BinanceTradeService.placeMarketOrder(BinanceTradeService.java:101)
	at tech.cassandre.trading.bot.service.TradeServiceXChangeImplementation.createMarketOrder(TradeServiceXChangeImplementation.java:100)
	at tech.cassandre.trading.bot.service.TradeServiceXChangeImplementation.createSellMarketOrder(TradeServiceXChangeImplementation.java:224)
	at tech.cassandre.trading.bot.service.PositionServiceCassandreImplementation.closePosition(PositionServiceCassandreImplementation.java:173)
	at tech.cassandre.trading.bot.strategy.GenericCassandreStrategy.lambda$updatePositionsWithTickersUpdates$26(GenericCassandreStrategy.java:473)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at tech.cassandre.trading.bot.strategy.GenericCassandreStrategy.updatePositionsWithTickersUpdates(GenericCassandreStrategy.java:473)
	at tech.cassandre.trading.bot.strategy.BasicTa4jCassandreStrategy.tickersUpdates(BasicTa4jCassandreStrategy.java:140)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:476)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:267)
	at reactor.core.publisher.FluxCreate$LatestAsyncSink.drain(FluxCreate.java:954)
	at reactor.core.publisher.FluxCreate$LatestAsyncSink.next(FluxCreate.java:878)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at tech.cassandre.trading.bot.util.base.batch.BaseFlux.emitValues(BaseFlux.java:67)
	at tech.cassandre.trading.bot.util.base.batch.BaseFlux.update(BaseFlux.java:76)
	at tech.cassandre.trading.bot.configuration.ScheduleAutoConfiguration.tickerFluxUpdate(ScheduleAutoConfiguration.java:94)
	at jdk.internal.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.knowm.xchange.binance.dto.BinanceException: Precision is over the maximum defined for this asset. (HTTP status code: 400)
	at jdk.internal.reflect.GeneratedConstructorAccessor99.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:291)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:288)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:454)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
2021-11-30 14:13:23.883 ERROR 1 --- [assandre-flux-2] .t.b.s.TradeServiceXChangeImplementation : TradeService - Error calling createMarketOrder for 2383222.00000000 SHIB/EUR: Precision is over the maximum defined for this asset. (HTTP status code: 400)

**Comment by straumat** [comment]
@xblaatx the error seems to come from XChange. What is strange is that it worked for buying no? 
As you used the position system, it means that the buying order creation worked and it failed making the selling order with the same amount. It doesn't seem "logic" no ?

**Comment by xblaatx** [comment]
Indeed it worked for buying. But not for selling that position.

Wierd. I have no idea why.

**Comment by straumat** [comment]
@xblaatx can you ask Binance support if it's normal?

**Comment by xblaatx** [comment]
@straumat Will do!

If i'm correct they specify the wrong decimal precision for shiba.

if you do.
`curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbol=SHIBEUR"`

you can see this:

"symbol": "SHIBEUR",
"baseAsset": "SHIB",
"baseAssetPrecision": 2

**Comment by xblaatx** [comment]
@straumat 

I checked with binance. their information is correct.
I also checked with Xchange. they do not handle any precision when making an order. They do provide that information in metaData for that currency pair.

So in other words it is cassandre's responsibility to concern about precision. The most currencies have a precision of 8. only a few differ from that.

My suggestion is to add 2 properties in CurrencyPairDTO. baseCurrencyPrecision and quoteCurrencyPrecision.
and alter the closePosition method so it uses this to.

**Comment by straumat** [comment]
@xblaatx a simple question, wouldn't it be easier to just remove the zeros when I send the order ?

**Comment by straumat** [comment]
To be more clear, Cassandre will set 2383222.00000000 as the amount when creating the selling order of the position. From what I understand, Binance is not happy to see so much 0, do you think a simple solution would be for cassandre use 2383222 as parameter ? (and so removing trailing zeros)

**Comment by xblaatx** [comment]
@straumat 

That could be a solution to.
But how are you gonna ensure that is always max 2 decimal digits?

example taken from the orderClose method: 
final BigDecimal amountToBuy = positionDTO.getAmountToLock().getValue().divide(ticker.getLast(), HALF_UP).setScale(SCALE, FLOOR);

**Comment by straumat** [comment]
@xblaatx I let you close this issue when you will have finish your test. Thx again

**Comment by straumat** [comment]
@xblaatx did you have time to try?

**Comment by straumat** [comment]
@xblaatx is it the same problem than #852 ? Can I close this one to focus on the other one ?

**Comment by xblaatx** [comment]
@straumat. That is fine.
